Year3/ClientServer/MatinloAdventures/MatinloAdventures.Web/Models/TourPackages/TourPackageIndexModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MatinloAdventures.Data.Models;

namespace MatinloAdventures.Web.Models.TourPackages
{
    public class TourPackageIndexModel
    {
        public List<IGrouping<string, MatinloAdventures.Data.Models.TourPackage>> TourPackages { get; set; }
        public List<TourPackageComment> Comments { get; set; }

        public string Username { get; set; }
        public string Email { get; set; }
    }
}

Year3/ClientServer/MatinloAdventures/MatinloAdventures.Web/Controllers/TourPackagesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MatinloAdventures.Data.Models;
using MatinloAdventures.Services.Contracts;
using MatinloAdventures.Web.Models.TourPackages;
using Microsoft.AspNetCore.Identity;

namespace MatinloAdventures.Web.Controllers
{
    public class TourPackagesController : Controller
    {
        private readonly IGenericDataService<TourPackage> _tourPackages;
        private readonly IGenericDataService<TourPackageComment> _tourPackageComments;
        private readonly UserManager<ApplicationUser> _users;

        public TourPackagesController(IGenericDataService<TourPackage> tourPackages, IGenericDataService<TourPackageComment> comments, UserManager<ApplicationUser> users)
        {
            _tourPackages = tourPackages;
            _tourPackageComments = comments;
            _users = users;
        }

        // GET: TourPackages
        public async Task<IActionResult> Index()
        {
            var allTourPackages = await _tourPackages.GetAllAsync();
            var grouped = allTourPackages.GroupBy(x => x.Destination).ToList();

            var loggedUser = User.Identity.IsAuthenticated ? await _users.FindByNameAsync(User.Identity.Name) : null;

            TourPackageIndexModel model = new TourPackageIndexModel();
            model.Comments = await _tourPackageComments.GetAllAsync();
            model.TourPackages = grouped;

            if (null != loggedUser)
            {
                model.Email = loggedUser.Email;
                model.Username = loggedUser.UserName;
            }

            return View(model);
        }

        // GET: TourPackages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tourPackage = await _tourPackages.GetSingleOrDefaultAsync(m => m.Id == id);
            if (tourPackage == null)
            {
                return NotFound();
            }

            return View(tourPackage);
        }

        // GET: TourPackages/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TourPackages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Destination,TransportationPrice,AccomodationPrice,AdventuresPrice")] TourPackage tourPackage)
        {
            if (ModelState.IsValid)
            {
                _tourPackages.Add(tourPackage);
                return RedirectToAction(nameof(Index));
            }
            return View(tourPackage);
        }

        // POST: TourPackages/CreateComment
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        [HttpPost]
        public async Task<IActionResult> CreateComment([FromBody]TourPackageComment tourPackageComment)
        {
            if (ModelState.IsValid)
            {
                tourPackageComment.DateCreated = DateTime.Now;

                //check for currently logged in user
                var existingUser = await _users.FindByNameAsync(tourPackageComment.Username.ToLower());

                //check if user is in database
                if (null != existingUser)
                {
                    tourPackageComment.Username = existingUser.UserName;
                    tourPackageComment.User = existingUser;
                }

                _tourPackageComments.Add(tourPackageComment);

                return Ok();
            }

            return NotFound();
        }

        // GET: TourPackages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tourPackage = await _tourPackages.GetSingleOrDefaultAsync(x => x.Id == id);
            if (tourPackage == null)
            {
                return NotFound();
            }
            return View(tourPackage);
        }

        // POST: TourPackages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Destination,TransportationPrice,AccomodationPrice,AdventuresPrice")] TourPackage tourPackage)
        {
            if (id != tourPackage.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _tourPackages.Update(tourPackage);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await TourPackageExists(tourPackage.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tourPackage);
        }

        // GET: TourPackages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tourPackage = await _tourPackages.GetSingleOrDefaultAsync(m => m.Id == id);
            if (tourPackage == null)
            {
                return NotFound();
            }

            return View(tourPackage);
        }

        // POST: TourPackages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            var tourPackage = await _tourPackages.GetSingleOrDefaultAsync(x=> x.Id == id);
            _tourPackages.Remove(tourPackage);

            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> TourPackageExists(int? id)
        {
            return await _tourPackages.AnyAsync(e => e.Id == id);
        }
    }
}

Year3/ClientServer/MatinloAdventures/MatinloAdventures.Web/Views/TourPackages/Create.cshtml
@model MatinloAdventures.Data.Models.TourPackage

@{
    ViewData["Title"] = "Create";
}

<div class="wrapper row3">
    <main class="hoc container clear">
        <h2>Create TourPackage</h2>
        <hr/>

        <div>
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control"/>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Destination" class="control-label"></label>
                    <input asp-for="Destination" class="form-control"/>
                    <span asp-validation-for="Destination" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TransportationPrice" class="control-label"></label>
                    <input asp-for="TransportationPrice" class="form-control"/>
                    <span asp-validation-for="TransportationPrice" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AccomodationPrice" class="control-label"></label>
                    <input asp-for="AccomodationPrice" class="form-control"/>
                    <span asp-validation-for="AccomodationPrice" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AdventuresPrice" class="control-label"></label>
                    <input asp-for="AdventuresPrice" class="form-control"/>
                    <span asp-validation-for="AdventuresPrice" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-default"/>
                    <a asp-action="Index" class="btn btn-default">Цени</a>
                </div>
            </form>
        </div>


    </main>
</div>

Year3/ClientServer/MatinloAdventures/MatinloAdventures.Web/Views/TourPackages/Delete.cshtml
@model MatinloAdventures.Data.Models.TourPackage

@{
    ViewData["Title"] = "Delete";
}


<div class="wrapper row3">
    <main class="hoc container clear">
        <h2>Delete TourPackage</h2>
        <h3>Are you sure you want to delete this?</h3>
        <hr/>

        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.TransportationPrice)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.TransportationPrice)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.AccomodationPrice)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.AccomodationPrice)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.AdventuresPrice)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.AdventuresPrice)
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="Name"/>
            <input type="hidden" asp-for="Destination"/>
            <input type="submit" value="Delete" class="btn btn-default"/>
            <a asp-action="Index" class="btn btn-default">Back to List</a>
        </form>
    </main>
</div>

Year3/ClientServer/MatinloAdventures/MatinloAdventures.Web/Views/TourPackages/Details.cshtml
@model MatinloAdventures.Data.Models.TourPackage

@{
    ViewData["Title"] = "Details";
}

<div class="wrapper row3">
    <main class="hoc container clear">
        <h2>Details TourPackage</h2>
        <hr/>

        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.TransportationPrice)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.TransportationPrice)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.AccomodationPrice)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.AccomodationPrice)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.AdventuresPrice)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.AdventuresPrice)
            </dd>
        </dl>
        
        <div>
            <a asp-action="Edit" class="btn" asp-route-id="@Model.Id">Edit</a>
            <a asp-action="Index" class="btn">Back to List</a>
        </div>
    </main>
</div>

Year3/ClientServer/MatinloAdventures/MatinloAdventures.Web/Views/TourPackages/Edit.cshtml
@model MatinloAdventures.Data.Models.TourPackage

@{
    ViewData["Title"] = "Edit";
}


<div class="wrapper row3">
    <main class="hoc container clear">
        <h2>Edit TourPackage</h2>
        <hr/>

        <div>
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Name"/>
                <input type="hidden" asp-for="Destination"/>
                <div class="form-group">
                    <label asp-for="TransportationPrice" class="control-label"></label>
                    <input asp-for="TransportationPrice" class="form-control"/>
                    <span asp-validation-for="TransportationPrice" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AccomodationPrice" class="control-label"></label>
                    <input asp-for="AccomodationPrice" class="form-control"/>
                    <span asp-validation-for="AccomodationPrice" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AdventuresPrice" class="control-label"></label>
                    <input asp-for="AdventuresPrice" class="form-control"/>
                    <span asp-validation-for="AdventuresPrice" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-default"/>
                    <a asp-action="Index" class="btn btn-default">Back to List</a>

                </div>
            </form>
        </div>
    </main>
</div>

Year3/ClientServer/MatinloAdventures/MatinloAdventures.Web/Views/TourPackages/Index.cshtml
@model MatinloAdventures.Web.Models.TourPackages.TourPackageIndexModel

@{
    ViewData["Title"] = "Index";
}

<div class="wrapper row3">

    <main class="hoc container clear">
        <!-- main body -->
        <!-- ################################################################################################ -->
        <div class="content">
            <!-- ################################################################################################ -->
            <h1>Среден ценоразпис за едно пътешествие</h1>
            <img class="imgr borderedbox inspace-5" src="../images/demo/imgr.gif" alt="">
            <p>Aenean gravida elit risus, ac rhoncus nunc molestie ac. Quisque vehicula nibh dui, a ultricies ex eleifend quis. In in auctor diam. Mauris dictum sem sem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut vel porttitor purus.</p>
            <p>Dapiensociis <a href="#">temper donec auctortortis cumsan</a> et curabitur condis lorem loborttis leo. Ipsumcommodo libero nunc at in velis tincidunt pellentum tincidunt vel lorem.</p>
            <img class="imgl borderedbox inspace-5" src="../images/demo/imgl.gif" alt="">
            <p>Aenean diam enim, venenatis nec auctor in, accumsan vitae sem. Aliquam quis neque lacinia, ultricies turpis vel, viverra neque. Maecenas aliquam, urna eu hendrerit imperdiet, felis felis dapibus tellus, sit amet efficitur tortor urna at nulla. Sed vestibulum pretium magna, vel lobortis ante viverra lacinia.</p>
            <p>Mauris erat felis, ultrices ac pellentesque eget, volutpat sit amet enim. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam quam eros, mollis non tellus ut, vehicula malesuada nunc. Sed gravida est ac libero posuere consectetur.</p>
            <p>Portortornec condimenterdum eget consectetuer condis consequam pretium pellus sed mauris enim. Puruselit mauris nulla hendimentesque elit semper nam a sapien urna sempus.</p>
            <h1>Цени</h1>
            @if (User.IsInRole("Admin"))
            {
                <a asp-action="Create" class="btn btn-success">Create New</a>
            }

            <hr/>
            <div class="scrollable">
                @foreach (var tourPackage in Model.TourPackages)
                {
                    <h1>@tourPackage.Key</h1>

                    <table>
                        <thead>
                        <tr>
                            <th>Услуга / Пакет</th>
                            <th>Вътрешен транспорт*</th>
                            <th>Нощувка</th>
                            <th>Приключения **</th>
                            @if (User.IsInRole("Admin"))
                            {
                                <th>Actions</th>
                            }
                        </tr>
                        </thead>
                        <tbody>
                        @foreach (var item in tourPackage)
                        {
                            <tr>
                                <td>@item.Name</td>
                                <td>@item.TransportationPrice &euro;</td>
                                <td>@item.AccomodationPrice &euro;</td>
                                <td>
                                    <a href="#">@item.AdventuresPrice &euro;</a>
                                </td>
                                @if (User.IsInRole("Admin"))
                                {
                                    <td>
                                        <a asp-area="" asp-controller="TourPackages" asp-action="Edit" asp-route-id="@item.Id" class="btn-default">Edit</a>
                                        <a asp-area="" asp-controller="TourPackages" asp-action="Details" asp-route-id="@item.Id" class="btn-info">Details</a>
                                        <a asp-area="" asp-controller="TourPackages" asp-action="Delete" asp-route-id="@item.Id" class="btn-danger">Delete</a>
                                    </td>
                                }
                            </tr>
                        }
                        </tbody>
                    </table>

                    <hr/>
                }
            </div>

            <div id="comments">
                <h2>Comments</h2>
                <ul id="prices-comments-ul">
                    @foreach (var comment in Model.Comments)
                    {
                        <li>
                            <article>
                                <header>
                                    <figure class="avatar">
                                        <img src="../images/demo/avatar.png" alt="">
                                    </figure>
                                    <address>
                                        By <a href="#">@comment.Username</a>
                                    </address>
                                    <time>@comment.DateCreated</time>
                                </header>
                                <div class="comcont">
                                    <p>@comment.Content</p>
                                </div>
                            </article>
                        </li>
                    }
                </ul>

                <h2>Write A Comment</h2>
                <form>
                    <div class="one_third first">
                        <label for="name">Name <span>*</span></label>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <input type="text" name="name" id="name" value="@Model.Username" size="22" required disabled>
                        }
                        else
                        {
                            <input type="text" name="name" id="name" value="" size="22" required>
                        }
                    </div>
                    <div class="one_third">
                        <label for="email">Mail <span>*</span></label>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <input type="email" name="email" id="email" value="@Model.Email" size="22" required disabled>
                        }
                        else
                        {
                            <input type="email" name="email" id="email" value="" size="22" required>
                        }
                    </div>
                    <div class="one_third">
                        <label for="url">Website</label>
                        <input type="url" name="url" id="url" value="" size="22">
                    </div>
                    <div class="block clear">
                        <label for="comment">Your Comment</label>
                        <textarea name="comment" id="comment" cols="25" rows="10"></textarea>
                    </div>
                    <div>
                        <input type="button" onclick="addCommentLi()" name="submit" value="Submit Comment">
                        &nbsp;
                    </div>
                </form>
            </div>
            <!-- ################################################################################################ -->
        </div>
        <!-- ################################################################################################ -->
        <!-- / main body -->
        <div class="clear"></div>
    </main>
</div>

@section Scripts
{
    <script src="~/js/prices.js"></script>
}